# Generated by Django 4.1 on 2022-09-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_M', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
